model:
  base_learning_rate: 5e-04
  target: ldm.models.autoencoders.model_for_visa2.VQModel
  params:
    # backbone: "resnet50"
    backbone: "wide_resnet50_2"
    image_size: 256
    feature_dims: [256, 512, 1024, 2048]
    pos_dims: [0, 0, 0, 0]
    n_embeds: [64, 64, 64, 64]
    folds: [8, 4, 2, 1]
    monitor: val/metric

    ddconfig:
      double_z: false
      z_channels: 2048
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 64
      ch_mult:
      - 1
      - 4
      - 8
      - 16
      - 32
      down_samples: [1,4,2,2,2]
      num_res_blocks: [1,4,6,3,1]
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: ldm.models.autoencoders.losses.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 0
        disc_weight: 0.75
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 16
    train:
      target: ldm.data.visa2.MemSegDataset
      params:
        datadir: '/data/arima/VisA'
        target: 'cashew'
        train: True
        texture_source_dir: '/data/arima/dtd/images'
    validation:
      target: ldm.data.visa2.MemSegDataset
      params:
        datadir: '/data/arima/VisA'
        target: 'cashew'
        train: False
        texture_source_dir: '/data/arima/dtd/images'
    test:
      target: ldm.data.visa2.MemSegDataset
      params:
        datadir: '/data/arima/VisA'
        target: 'cashew'
        train: False
        texture_source_dir: '/data/arima/dtd/images'
