model:
  base_learning_rate: 4.5e-06
  # target: ldm.models.autoencoders.autoencoder.VQModel
  target: ldm.models.autoencoders.ml_ae.VQModel
  params:
    # backbone: "resnet50"
    backbone: "wide_resnet50_2"
    # embed_dims: [384, 640, 1280, 2304]
    # pos_dims: [128, 128, 256, 256]
    embed_dims: [256, 512, 1024, 2048]
    pos_dims: [0, 0, 0, 0]
    n_embeds: [8192, 2048, 512, 128]
    monitor: val/auroc

    ddconfig:
      double_z: false
      z_channels: 2048
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 64
      ch_mult:
      - 1
      - 4
      - 8
      - 16
      - 32
      down_samples: [1,4,2,2,2]
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: ldm.models.autoencoders.losses.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 0
        disc_weight: 0.75
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 16
    # wrap: true
    train:
      target: ldm.data.mvtec.MVTec
      params:
        data_path: '/data/arima/MVTec-AD/pill'
    validation:
      target: ldm.data.mvtec.MVTec_validate
      params:
        data_path: '/data/arima/MVTec-AD/pill'
